#!/usr/bin/env node
// JSON Schema → Zod codegen for the Demo Document.
//
// The Pydantic models in `walkthru/core/schema.py` are the SSOT (see DECISIONS §D1). They emit
// `schema/demo-document.schema.json`, which is the ONLY thing crossing the Python↔TS boundary.
// This script turns that committed JSON Schema into a Zod schema the TS side validates against.
//
//   schema/demo-document.schema.json  →  ts/src/schema.generated.ts
//     exports: `demoDocumentSchema` (Zod), `DemoDocument` (post-parse type), `DemoDocumentInput`
//     (pre-parse type — fields with schema defaults are optional).
//
// We deliberately consume the committed JSON Schema artifact rather than reaching into Python —
// the TS side stays runnable with no Python toolchain, and the core/adapter firewall holds
// (TS depends on the JSON contract, never on `walkthru`/`reelee`/`lacing`). This mirrors the
// federation's tool choice (reelee-web uses the same `json-schema-to-zod` + zod v4) without
// importing reelee's `export-schemas`/lacing machinery.
//
// Regenerate after the Pydantic models change:
//   1. (Python) regenerate schema/demo-document.schema.json  — guarded by
//      tests/test_schema.py::test_committed_json_schema_is_up_to_date
//   2. (TS)     npm run codegen
//
// `--check` regenerates in memory and exits non-zero if the committed output is stale, without
// writing — the drift guard CI (and the vitest codegen test) run this so the committed Zod can
// never silently fall behind the JSON Schema.

import $RefParser from '@apidevtools/json-schema-ref-parser';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TS_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(TS_ROOT, '..');
const INPUT = resolve(REPO_ROOT, 'schema/demo-document.schema.json');
const OUTPUT = resolve(TS_ROOT, 'src/schema.generated.ts');
const EXPORT_NAME = 'demoDocumentSchema';
const TYPE_NAME = 'DemoDocument';

const HEADER =
  '// GENERATED by ts/scripts/codegen.mjs from schema/demo-document.schema.json — do not edit.\n' +
  '// The Pydantic models in walkthru/core/schema.py are the SSOT; regenerate with `npm run codegen`.\n\n';

// json-schema-to-zod emits only the `z.infer` (post-parse / OUTPUT) type. That type is right for a
// value you got *back* from `demoDocumentSchema.parse(...)` — every field carrying a `.default(...)`
// is guaranteed present — but wrong for a literal you are about to pass *in*: it forces you to spell
// out `kind`, `params`, `holdAfterMs`, `schemaVersion` … that the runtime fills for you (issue #24).
// So we also emit the `z.input` (pre-parse) twin, where defaulted fields are optional.
//
// Both are exported on purpose; the alias is NOT swapped. `DemoDocument` stays the post-parse type
// because that is what `parse()` returns and what the README annotates.
const FOOTER =
  '\n' +
  `// The pre-parse twin of \`${TYPE_NAME}\`: fields the schema defaults are OPTIONAL here.\n` +
  '// Annotate object literals you are constructing with this; annotate values returned by\n' +
  `// \`${EXPORT_NAME}.parse(...)\` with \`${TYPE_NAME}\`, where those fields are guaranteed present.\n` +
  `export type ${TYPE_NAME}Input = z.input<typeof ${EXPORT_NAME}>\n`;

class CodegenError extends Error {}

/**
 * Build the full `schema.generated.ts` module text from the committed JSON Schema.
 *
 * Pydantic emits nested models as `$ref` into `$defs`. json-schema-to-zod (CLI *and* programmatic
 * API) renders unresolved `$ref`s as `z.any()` — it does not dereference. So we inline every
 * `$ref` first. The Demo Document schema is a DAG (no cycles; `Target` etc. just fan out), so a
 * full dereference is safe and yields a self-contained schema json-schema-to-zod can fully map.
 *
 * Exported so both the CLI below and the vitest drift guard generate via one code path (SSOT).
 */
export async function buildModule() {
  if (!existsSync(INPUT)) {
    throw new CodegenError(
      `missing ${INPUT}\nRegenerate the Pydantic-emitted JSON Schema first (walkthru/core/schema.py).`,
    );
  }
  const schema = await $RefParser.dereference(JSON.parse(readFileSync(INPUT, 'utf8')));
  const code = jsonSchemaToZod(schema, { name: EXPORT_NAME, module: 'esm', type: TYPE_NAME });
  return HEADER + code + '\n' + FOOTER;
}

/** The committed module text, or null if it has not been generated yet. */
export function committedModule() {
  return existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : null;
}

export { OUTPUT, INPUT };

// --- CLI -----------------------------------------------------------------
// Run only when invoked directly (not when imported by the drift-guard test).
if (resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  try {
    const fresh = await buildModule();
    if (check) {
      if (committedModule() !== fresh) {
        console.error(
          `codegen: ${OUTPUT} is STALE — run \`npm run codegen\` and commit the result.`,
        );
        process.exit(1);
      }
      console.log('codegen: committed schema is up to date ✓');
    } else {
      writeFileSync(OUTPUT, fresh);
      console.log(`codegen: wrote ${EXPORT_NAME} to ${OUTPUT}`);
    }
  } catch (err) {
    console.error(`codegen: ${err.message}`);
    process.exit(1);
  }
}
