"""walkthru's pure core: the Demo Document schema, the lifecycle events, and the engine.

Nothing in this package imports from :mod:`walkthru.adapters` or :mod:`walkthru.ecosystem`, and it
has no vendor dependencies — only Pydantic (for the schema SSOT). Import the engine and schema from
here or from the top-level :mod:`walkthru` package.
"""

from walkthru.core.engine import iter_events, play, record
from walkthru.core.timeline import (
    ResolvedCamera,
    ResolvedCue,
    ResolvedNarration,
    ResolvedStep,
    Timeline,
    iter_resolved_steps,
    resolve_timeline,
)
from walkthru.core.events import (
    AfterCommand,
    BeatEvent,
    BeforeCommand,
    CommandError,
    CommandInvocation,
    CueBegin,
    CueEnd,
    DemoEnd,
    DemoStart,
    Event,
    Narration,
    Observer,
    Outcome,
    SectionEnter,
    SectionExit,
    StepEnter,
    StepExit,
)
from walkthru.core.schema import (
    Anchor,
    AssetRef,
    Beat,
    CalloutCue,
    CameraKeyframe,
    Command,
    CommandStep,
    Cue,
    CursorCue,
    DemoDocument,
    HighlightCue,
    HotspotCue,
    Locator,
    Meta,
    NarrationAnchor,
    NarrationSegment,
    Rect,
    Section,
    SpotlightCue,
    Step,
    Target,
    Timing,
    Tracks,
    demo_document_json_schema,
)

__all__ = [
    # engine
    "play",
    "record",
    "iter_events",
    # timeline
    "resolve_timeline",
    "iter_resolved_steps",
    "Timeline",
    "ResolvedStep",
    "ResolvedCue",
    "ResolvedNarration",
    "ResolvedCamera",
    # schema
    "DemoDocument",
    "Meta",
    "Section",
    "Step",
    "CommandStep",
    "Beat",
    "Command",
    "Timing",
    "Anchor",
    "Target",
    "Locator",
    "Rect",
    "Tracks",
    "Cue",
    "HighlightCue",
    "SpotlightCue",
    "HotspotCue",
    "CalloutCue",
    "CursorCue",
    "NarrationSegment",
    "NarrationAnchor",
    "CameraKeyframe",
    "AssetRef",
    "demo_document_json_schema",
    # events
    "Event",
    "Observer",
    "Outcome",
    "CommandInvocation",
    "DemoStart",
    "DemoEnd",
    "SectionEnter",
    "SectionExit",
    "StepEnter",
    "StepExit",
    "BeforeCommand",
    "AfterCommand",
    "CommandError",
    "CueBegin",
    "CueEnd",
    "Narration",
    "BeatEvent",
]
